### ISSUE TITLE
Can I run it on kubernetes ?

### ISSUE THREAD

**Issue by jwalitptl** [loreste/karl#1]
Hi there! Thanks foe the great work. most of the media server has limitation on running kubernetes. how this one different ?

**Comment by loreste** [comment]
Hi @jwalitptl, great question!

Karl was specifically designed with containerized and Kubernetes deployments in mind. Here's what makes it different from traditional media servers like rtpengine:

## No Kernel Modules Required

Unlike rtpengine, Karl runs entirely in userspace. There's no `xt_RTPENGINE` kernel module to compile, no DKMS headaches, and no need for privileged containers. This is the single biggest advantage for Kubernetes deployments.

## Kubernetes-Ready Features

Karl includes several features that make it cloud-native:

- **Health Endpoints**: Liveness and readiness probes at `/health` and `/health/detail`
- **Prometheus Metrics**: Full observability at `:9091/metrics`
- **Graceful Shutdown**: Proper SIGTERM handling for pod termination
- **Stateless Design**: Session state can be externalized to Redis for horizontal scaling
- **Single Binary**: No complex dependencies to manage

## Example Kubernetes Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karl
  template:
    metadata:
      labels:
        app: karl
    spec:
      containers:
      - name: karl
        image: loreste/karl:latest
        ports:
        - containerPort: 22222
          protocol: UDP
        - containerPort: 8080
        - containerPort: 9091
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: karl
spec:
  type: LoadBalancer
  ports:
  - name: ng-protocol
    port: 22222
    protocol: UDP
  - name: api
    port: 8080
  - name: metrics
    port: 9091
  selector:
    app: karl
```

## RTP Port Considerations

The main consideration for Kubernetes is RTP media ports (default 30000-40000). You have a few options:

1. **Host Network Mode**: Use `hostNetwork: true` for direct port access (simplest)
2. **NodePort Range**: Configure Karl's port range to match Kubernetes NodePort range
3. **MetalLB/Load Balancer**: For bare-metal clusters with UDP support

## What's Coming

We're actively working on:
- Redis-based session clustering for true horizontal scaling
- Helm chart for easy deployment
- Kubernetes operator for advanced management

Let me know if you have any other questions!
